name: 'Deploy'
on:
  push:
    branches:
    - "main"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-20.04
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
#       with: 
#          terraform_version: ${{ env.TERRAFORM_VERSION }}
    #         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    
    - name: Terraform init
      run: |
        cd terraform-code
        terraform init
    - name: "terraform: apply"
      run: |
        cd terraform-code
        terraform apply --auto-approve
